name: Container on Fly.io

on:
  workflow_call:
    inputs:
      staging_app_name:
        description: Staging Fly.io app name, optional when already specified in the fly.toml
        type: string
        required: false

      production_app_name:
        description: Production Fly.io app name, optional when already specified in the fly.toml
        type: string
        required: false

      staging_branch:
        description: Branch used to deploy to staging
        type: string
        default: main

      staging_fly_config_path:
        description: Path to the fly config for the staging environment
        type: string
        default: fly.toml

      production_fly_config_path:
        description: Path to the fly config for the staging environment
        type: string
        default: fly.toml

      lint_fly_config:
        description: If we should lint the fly.toml config.
        type: boolean
        default: true

    secrets:
      FLY_API_TOKEN_STAGING:
        required: false
      FLY_API_TOKEN_PRODUCTION:
        required: false

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

jobs:
  lint-fly-config:
    name: Lint Fly config
    if: inputs.lint_fly_config
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - uses: actions/checkout@v4

      - run: flyctl config validate --config "${{ inputs.staging_fly_config_path }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}

      - run: flyctl config validate --config "${{ inputs.production_fly_config_path }}"
        if: inputs.staging_fly_config_path != inputs.production_fly_config_path
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}

  build-and-deploy:
    name: Fly deploy
    needs:
      - lint-fly-config
    if: |
      github.event_name == 'release' || 
      (
        github.event_name == 'push' || 
        github.event_name == 'workflow_dispatch'
      ) && github.ref_name == inputs.staging_branch
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-fly-deploy-${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to staging
        if: inputs.staging_app_name && github.ref_name == inputs.staging_branch
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
          FLY_APP: ${{ inputs.staging_app_name }}
        run: |
          flyctl deploy \
            --remote-only \
            --build-arg APP_VERSION="0.0.1-staging-${{ github.sha }}"

      - name: Deploy to production
        if: inputs.production_app_name && github.event_name == 'release'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PRODUCTION }}
          FLY_APP: ${{ inputs.production_app_name }}
        run: |
          flyctl deploy \
            --remote-only \
            --build-arg APP_VERSION="${{ github.ref_name }}"
