name: Vercel app

on:
  workflow_call:
    inputs:
      install_command:
        description: Install command.
        type: string
        required: false
        default: npm ci --prefer-offline --no-audit --no-fund

      lint_command:
        description: Lint command.
        type: string
        required: false
        default: npm run lint
      
      test_command:
        description: Test command.
        type: string
        required: false
        default: npm run test

      npm_scope:
        description: "NPM scope (containing the '@' symbol, ex: @example)."
        type: string
        required: false
        default: null

      install_registry_url:
        description: >-
          The NPM registry URL to install scoped packages from.
          Scope specified in the input `npm_scope`.
          For example `https://registry.npmjs.org/` for the official NPM registry
          or `https://npm.pkg.github.com/` for GitHub's registry.
        required: false
        default: null
        type: string

      staging_domain:
        description: Staging domain (preview domain for the main branch).
        required: false
        type: string

      production_domain:
        description: Production domain (domain to be applied for the production releases).
        required: false
        type: string

      vercel_scope:
        description: Vercel team scope, required for custom domain aliases.
        required: false
        type: string
        default: significa

    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Custom checks to configs
        run: |
          [ -f "./.nvmrc" ] || (echo "Required .nvmrc file does not exist" >&2 && echo 1)
          [ -f "./vercel.json" ] || (echo "Required vercel.json file does not exist" >&2 && echo 1)

      - name: Delete commited .npmrc
        run: rm .npmrc

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          scope: ${{ inputs.npm_scope }}
          registry-url: ${{ inputs.install_registry_url }}

      - name: Install dependencies
        run: ${{ inputs.install_command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        if: inputs.lint_command
        run: ${{ inputs.lint_command }}

      - name: Test
        if: inputs.test_command
        run: ${{ inputs.test_command }}
  
  build-and-depploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    permissions:
      deployments: write
      contents: read
      packages: read
    needs:
      - test-and-lint
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          scope: ${{ inputs.npm_scope }}
          registry-url: ${{ inputs.install_registry_url }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to vercel
        if: |
          github.event_name == 'release'
          && startsWith(github.event.release.name, 'v')
          && startsWith(github.event.release.tag_name, 'v')
        run: |
          vercel pull --yes \
            --environment=production \
            --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy to vercel
        if: github.event_name != 'release'
        run: |
          vercel pull --yes \
            --environment=preview \
            --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Build Project Artifacts
        run: |
          vercel build --yes \
            --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel_deploy
        shell: bash
        run: |
          vercel deploy --yes \
            --prebuilt \
            --token="${{ secrets.VERCEL_TOKEN }}" \
            --name="${{ github.ref_name }}" \
          | tee >(tail -1 | sed -e 's/^/preview_url=/;' >> "$GITHUB_OUTPUT")

      - name: Set deployment alias (staging)
        if: |
          inputs.staging_domain
          && github.event_name != 'pull_request'
          && ${{ github.ref == 'refs/heads/main' }}
        run: |
          vercel alias set \
            '${{ steps.vercel_deploy.outputs.preview_url }}' \
            '${{ inputs.staging_domain }}' \
            --scope="${{ inputs.vercel_scope }}" \
            --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Set deployment alias (production)
        if: |
          inputs.production_domain
          && github.event_name == 'release'
          && startsWith(github.event.release.name, 'v')
          && startsWith(github.event.release.tag_name, 'v')
        run: |
          vercel alias set \
            '${{ steps.vercel_deploy.outputs.preview_url }}' \
            '${{ inputs.production_domain }}' \
            --scope="${{ inputs.vercel_scope }}" \
            --token="${{ secrets.VERCEL_TOKEN }}"

      - name: Create deployment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const response = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.event.pull_request.head.ref }}',
              auto_merge: false,
              environment: 'preview',
              production_environment: false,
              required_contexts: [],
            })

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: response.data.id,
              target_url: '${{ steps.vercel_deploy.outputs.preview_url }}',
              environment_url: '${{ steps.vercel_deploy.outputs.preview_url }}',
              state: 'success',
            });
